PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Clubs
CREATE TABLE Clubs (ID INTEGER PRIMARY KEY NOT NULL UNIQUE, Name VARCHAR UNIQUE NOT NULL);

-- Table: Players
CREATE TABLE Players (ID INTEGER PRIMARY KEY NOT NULL UNIQUE, Name VARCHAR (30) NOT NULL, Value DECIMAL, ClubID INTEGER CONSTRAINT FK_Clubs REFERENCES Clubs (ID), Position VARCHAR (5) CONSTRAINT pos CHECK (Position IN ('GKP', 'DEF', 'MID', 'FWD')), Nation VARCHAR);

-- Table: SquadMembers
CREATE TABLE SquadMembers (Squad INTEGER CONSTRAINT FK_SquadMmeber_Squad REFERENCES Squads (ID), Player INTEGER CONSTRAINT FK_SquadMember_Player REFERENCES Players (ID));

-- Table: Squads
CREATE TABLE Squads (ID INTEGER PRIMARY KEY NOT NULL UNIQUE, Name VARCHAR NOT NULL, Value DECIMAL, Owner INTEGER CONSTRAINT FK_Owner REFERENCES Users (ID));

-- Table: Users
CREATE TABLE Users (ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, Name VARCHAR (30) NOT NULL, Email VARCHAR (50) UNIQUE NOT NULL, Password VARCHAR (30) NOT NULL, FavTeam VARCHAR);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
